#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionQTest01
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Taximan")]
	public partial class TaxiManDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertCustUser(CustUser instance);
    partial void DeleteCustUser(CustUser instance);
    #endregion
		
		public TaxiManDBDataContext() : 
				base(global::LionQTest01.Properties.Settings.Default.TaximanConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TaxiManDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaxiManDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaxiManDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaxiManDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<CustUser> CustUsers
		{
			get
			{
				return this.GetTable<CustUser>();
			}
		}
		
		private void UpdateCustUser(CustUser obj)
		{
			System.Nullable<int> p1 = obj.UserID;
			string st = "";
			this.SaveCustUser(ref p1, ((System.Nullable<int>)(obj.OwnerID)), ((System.Nullable<int>)(obj.OwnerType)), obj.CustomerID, obj.Name, obj.ImportantNotes, obj.Notes, obj.LoyalPointsNum, obj.CustUserBarCode, ((System.Nullable<char>)(obj.Status)), obj.Title, obj.FirstName, obj.LastName, obj.Phone, obj.Fax, obj.CellPhone, obj.Email1, obj.Email2, ((System.Nullable<int>)(obj.HomeAddrID)), ((System.Nullable<int>)(obj.DriverRating)), ((System.Nullable<char>)(obj.Priority)), ((System.Nullable<char>)(obj.CallBack)), ((System.Nullable<char>)(obj.TextBack)), ((System.Nullable<char>)(obj.EmailBack)), obj.Position, obj.Web_LoginID, obj.Web_Password, ((System.Nullable<char>)(obj.WebReservation)), 
				ref st,//default(System.Nullable<char>), 
				((System.Nullable<char>)(obj.UserDefaultTripToSR)), default(System.Nullable<int>), ((System.Nullable<char>)(obj.AllowAltAddress)), ((System.Nullable<char>)(obj.CanBook4Other)), obj.VIPNum, ((System.Nullable<char>)(obj.ShowRemarkFlag)), ((System.Nullable<char>)(obj.ShowRegularTrips)), ((System.Nullable<char>)(obj.ReceiptBack)));
			obj.UserID = p1.GetValueOrDefault();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SaveCustUser")]
		public int SaveCustUser(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] ref System.Nullable<int> userID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="Int")] System.Nullable<int> ownerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerType", DbType="Int")] System.Nullable<int> ownerType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="VarChar(9)")] string customerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(25)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImportantNotes", DbType="VarChar(255)")] string importantNotes, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Notes", DbType="VarChar(255)")] string notes, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoyalPointsNum", DbType="VarChar(20)")] string loyalPointsNum, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustUserBarCode", DbType="VarChar(25)")] string custUserBarCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Char(1)")] System.Nullable<char> status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="VarChar(15)")] string title, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="VarChar(30)")] string firstName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="VarChar(30)")] string lastName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="VarChar(20)")] string phone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="VarChar(20)")] string fax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CellPhone", DbType="VarChar(20)")] string cellPhone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email1", DbType="VarChar(50)")] string email1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email2", DbType="VarChar(50)")] string email2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HomeAddrID", DbType="Int")] System.Nullable<int> homeAddrID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DriverRating", DbType="Int")] System.Nullable<int> driverRating, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Priority", DbType="Char(1)")] System.Nullable<char> priority, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CallBack", DbType="Char(1)")] System.Nullable<char> callBack, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TextBack", DbType="Char(1)")] System.Nullable<char> textBack, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailBack", DbType="Char(1)")] System.Nullable<char> emailBack, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Position", DbType="VarChar(30)")] string position, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Web_LoginID", DbType="VarChar(50)")] string web_LoginID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Web_Password", DbType="VarChar(100)")] string web_Password, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WebReservation", DbType="Char(1)")] System.Nullable<char> webReservation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustPhoneError", DbType="VarChar(100)")] ref string custPhoneError, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserDefaultTripToSR", DbType="Char(1)")] System.Nullable<char> userDefaultTripToSR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserLoadUnloadTime", DbType="Int")] System.Nullable<int> userLoadUnloadTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AllowAltAddress", DbType="Char(1)")] System.Nullable<char> allowAltAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CanBook4Other", DbType="Char(1)")] System.Nullable<char> canBook4Other, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VIPNum", DbType="VarChar(50)")] string vIPNum, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowRemarkFlag", DbType="Char(1)")] System.Nullable<char> showRemarkFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowRegularTrips", DbType="Char(1)")] System.Nullable<char> showRegularTrips, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceiptBack", DbType="Char(1)")] System.Nullable<char> receiptBack)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, ownerID, ownerType, customerID, name, importantNotes, notes, loyalPointsNum, custUserBarCode, status, title, firstName, lastName, phone, fax, cellPhone, email1, email2, homeAddrID, driverRating, priority, callBack, textBack, emailBack, position, web_LoginID, web_Password, webReservation, custPhoneError, userDefaultTripToSR, userLoadUnloadTime, allowAltAddress, canBook4Other, vIPNum, showRemarkFlag, showRegularTrips, receiptBack);
			userID = ((System.Nullable<int>)(result.GetParameterValue(0)));
			custPhoneError = ((string)(result.GetParameterValue(28)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CustomerID;
		
		private string _Status;
		
		private string _Company;
		
		private string _Contact;
		
		private string _Details;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _City;
		
		private string _Province;
		
		private string _Postal;
		
		private string _Phone;
		
		private string _PhoneAlt;
		
		private string _Type;
		
		private string _Notes;
		
		private string _ACC_NUM;
		
		private string _TAX_NUM;
		
		private string _TITLE;
		
		private string _FIRSTNAME;
		
		private string _MIDINITIAL;
		
		private string _FAX;
		
		private System.Nullable<System.DateTime> _MODIFDATE;
		
		private System.Nullable<int> _STAFFLOGID;
		
		private string _CC_NUMBER;
		
		private string _CC_EXPIRY;
		
		private string _CC_CARDHOLDER;
		
		private System.Nullable<int> _CC_ID;
		
		private System.Nullable<int> _CC_TEMPLATE;
		
		private System.Nullable<decimal> _FBALANCE;
		
		private System.Nullable<decimal> _EBALANCE;
		
		private System.Nullable<float> _DISCOUNT;
		
		private System.Nullable<int> _CLIENT_TYPE_ID;
		
		private System.Nullable<System.DateTime> _TRANSDATE;
		
		private string _LAST_INVOICE_NUM;
		
		private System.Nullable<int> _ACCTEMPLATEID;
		
		private System.Nullable<int> _BrokerID;
		
		private System.Nullable<int> _TYPEPRNINVOICE_ID;
		
		private System.Nullable<char> _ApplyCC;
		
		private string _ClassID;
		
		private System.Nullable<int> _DriverRating;
		
		private System.Nullable<char> _DELETED;
		
		private int _PlanID;
		
		private int _HasPlan;
		
		private int _DefaultTemplateID;
		
		private string _DeletedBy;
		
		private System.Nullable<char> _Priority;
		
		private System.Nullable<System.DateTime> _EffDate;
		
		private System.Nullable<System.DateTime> _TilDate;
		
		private bool _Closed;
		
		private string _CustBarCode;
		
		private string _BillingContact;
		
		private System.Nullable<int> _PromptID;
		
		private int _ACCGROUP_ID;
		
		private int _BillingType;
		
		private string _InnerRemark;
		
		private string _CC_Start;
		
		private string _CC_IssueNumber;
		
		private string _CC_SecurityCode;
		
		private string _CC_Address;
		
		private System.Nullable<short> _AccType;
		
		private string _BusinessType;
		
		private System.Nullable<char> _DefaultTripToSR;
		
		private System.Nullable<int> _LoadUnloadTime;
		
		private char _AllowAltAddress;
		
		private string _RPFromPhone;
		
		private string _RPPickupPhone;
		
		private string _VipLabel;
		
		private char _CustUserReserv;
		
		private char _ShowRegularTrips;
		
		private char _BillingAccount;
		
		private char _IsWebAccount;
		
		private char _SkipZoneLandmarkPricingForAccounts;
		
		private System.Nullable<char> _RPAccDestAddrReq;
		
		private char _MDTAccSignReq;
		
		private EntitySet<CustUser> _CustUsers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCustomerIDChanging(string value);
    partial void OnCustomerIDChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnDetailsChanging(string value);
    partial void OnDetailsChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnPostalChanging(string value);
    partial void OnPostalChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnPhoneAltChanging(string value);
    partial void OnPhoneAltChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnACC_NUMChanging(string value);
    partial void OnACC_NUMChanged();
    partial void OnTAX_NUMChanging(string value);
    partial void OnTAX_NUMChanged();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    partial void OnFIRSTNAMEChanging(string value);
    partial void OnFIRSTNAMEChanged();
    partial void OnMIDINITIALChanging(string value);
    partial void OnMIDINITIALChanged();
    partial void OnFAXChanging(string value);
    partial void OnFAXChanged();
    partial void OnMODIFDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFDATEChanged();
    partial void OnSTAFFLOGIDChanging(System.Nullable<int> value);
    partial void OnSTAFFLOGIDChanged();
    partial void OnCC_NUMBERChanging(string value);
    partial void OnCC_NUMBERChanged();
    partial void OnCC_EXPIRYChanging(string value);
    partial void OnCC_EXPIRYChanged();
    partial void OnCC_CARDHOLDERChanging(string value);
    partial void OnCC_CARDHOLDERChanged();
    partial void OnCC_IDChanging(System.Nullable<int> value);
    partial void OnCC_IDChanged();
    partial void OnCC_TEMPLATEChanging(System.Nullable<int> value);
    partial void OnCC_TEMPLATEChanged();
    partial void OnFBALANCEChanging(System.Nullable<decimal> value);
    partial void OnFBALANCEChanged();
    partial void OnEBALANCEChanging(System.Nullable<decimal> value);
    partial void OnEBALANCEChanged();
    partial void OnDISCOUNTChanging(System.Nullable<float> value);
    partial void OnDISCOUNTChanged();
    partial void OnCLIENT_TYPE_IDChanging(System.Nullable<int> value);
    partial void OnCLIENT_TYPE_IDChanged();
    partial void OnTRANSDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnTRANSDATEChanged();
    partial void OnLAST_INVOICE_NUMChanging(string value);
    partial void OnLAST_INVOICE_NUMChanged();
    partial void OnACCTEMPLATEIDChanging(System.Nullable<int> value);
    partial void OnACCTEMPLATEIDChanged();
    partial void OnBrokerIDChanging(System.Nullable<int> value);
    partial void OnBrokerIDChanged();
    partial void OnTYPEPRNINVOICE_IDChanging(System.Nullable<int> value);
    partial void OnTYPEPRNINVOICE_IDChanged();
    partial void OnApplyCCChanging(System.Nullable<char> value);
    partial void OnApplyCCChanged();
    partial void OnClassIDChanging(string value);
    partial void OnClassIDChanged();
    partial void OnDriverRatingChanging(System.Nullable<int> value);
    partial void OnDriverRatingChanged();
    partial void OnDELETEDChanging(System.Nullable<char> value);
    partial void OnDELETEDChanged();
    partial void OnPlanIDChanging(int value);
    partial void OnPlanIDChanged();
    partial void OnHasPlanChanging(int value);
    partial void OnHasPlanChanged();
    partial void OnDefaultTemplateIDChanging(int value);
    partial void OnDefaultTemplateIDChanged();
    partial void OnDeletedByChanging(string value);
    partial void OnDeletedByChanged();
    partial void OnPriorityChanging(System.Nullable<char> value);
    partial void OnPriorityChanged();
    partial void OnEffDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEffDateChanged();
    partial void OnTilDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTilDateChanged();
    partial void OnClosedChanging(bool value);
    partial void OnClosedChanged();
    partial void OnCustBarCodeChanging(string value);
    partial void OnCustBarCodeChanged();
    partial void OnBillingContactChanging(string value);
    partial void OnBillingContactChanged();
    partial void OnPromptIDChanging(System.Nullable<int> value);
    partial void OnPromptIDChanged();
    partial void OnACCGROUP_IDChanging(int value);
    partial void OnACCGROUP_IDChanged();
    partial void OnBillingTypeChanging(int value);
    partial void OnBillingTypeChanged();
    partial void OnInnerRemarkChanging(string value);
    partial void OnInnerRemarkChanged();
    partial void OnCC_StartChanging(string value);
    partial void OnCC_StartChanged();
    partial void OnCC_IssueNumberChanging(string value);
    partial void OnCC_IssueNumberChanged();
    partial void OnCC_SecurityCodeChanging(string value);
    partial void OnCC_SecurityCodeChanged();
    partial void OnCC_AddressChanging(string value);
    partial void OnCC_AddressChanged();
    partial void OnAccTypeChanging(System.Nullable<short> value);
    partial void OnAccTypeChanged();
    partial void OnBusinessTypeChanging(string value);
    partial void OnBusinessTypeChanged();
    partial void OnDefaultTripToSRChanging(System.Nullable<char> value);
    partial void OnDefaultTripToSRChanged();
    partial void OnLoadUnloadTimeChanging(System.Nullable<int> value);
    partial void OnLoadUnloadTimeChanged();
    partial void OnAllowAltAddressChanging(char value);
    partial void OnAllowAltAddressChanged();
    partial void OnRPFromPhoneChanging(string value);
    partial void OnRPFromPhoneChanged();
    partial void OnRPPickupPhoneChanging(string value);
    partial void OnRPPickupPhoneChanged();
    partial void OnVipLabelChanging(string value);
    partial void OnVipLabelChanged();
    partial void OnCustUserReservChanging(char value);
    partial void OnCustUserReservChanged();
    partial void OnShowRegularTripsChanging(char value);
    partial void OnShowRegularTripsChanged();
    partial void OnBillingAccountChanging(char value);
    partial void OnBillingAccountChanged();
    partial void OnIsWebAccountChanging(char value);
    partial void OnIsWebAccountChanged();
    partial void OnSkipZoneLandmarkPricingForAccountsChanging(char value);
    partial void OnSkipZoneLandmarkPricingForAccountsChanged();
    partial void OnRPAccDestAddrReqChanging(System.Nullable<char> value);
    partial void OnRPAccDestAddrReqChanged();
    partial void OnMDTAccSignReqChanging(char value);
    partial void OnMDTAccSignReqChanged();
    #endregion
		
		public Customer()
		{
			this._CustUsers = new EntitySet<CustUser>(new Action<CustUser>(this.attach_CustUsers), new Action<CustUser>(this.detach_CustUsers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(1)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(50)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(30)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Details", DbType="VarChar(50)")]
		public string Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				if ((this._Details != value))
				{
					this.OnDetailsChanging(value);
					this.SendPropertyChanging();
					this._Details = value;
					this.SendPropertyChanged("Details");
					this.OnDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(255)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(255)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(30)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="VarChar(31)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this.OnProvinceChanging(value);
					this.SendPropertyChanging();
					this._Province = value;
					this.SendPropertyChanged("Province");
					this.OnProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postal", DbType="VarChar(9)")]
		public string Postal
		{
			get
			{
				return this._Postal;
			}
			set
			{
				if ((this._Postal != value))
				{
					this.OnPostalChanging(value);
					this.SendPropertyChanging();
					this._Postal = value;
					this.SendPropertyChanged("Postal");
					this.OnPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneAlt", DbType="VarChar(20)")]
		public string PhoneAlt
		{
			get
			{
				return this._PhoneAlt;
			}
			set
			{
				if ((this._PhoneAlt != value))
				{
					this.OnPhoneAltChanging(value);
					this.SendPropertyChanging();
					this._PhoneAlt = value;
					this.SendPropertyChanged("PhoneAlt");
					this.OnPhoneAltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(3)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(512)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACC_NUM", DbType="VarChar(15)")]
		public string ACC_NUM
		{
			get
			{
				return this._ACC_NUM;
			}
			set
			{
				if ((this._ACC_NUM != value))
				{
					this.OnACC_NUMChanging(value);
					this.SendPropertyChanging();
					this._ACC_NUM = value;
					this.SendPropertyChanged("ACC_NUM");
					this.OnACC_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAX_NUM", DbType="VarChar(15)")]
		public string TAX_NUM
		{
			get
			{
				return this._TAX_NUM;
			}
			set
			{
				if ((this._TAX_NUM != value))
				{
					this.OnTAX_NUMChanging(value);
					this.SendPropertyChanging();
					this._TAX_NUM = value;
					this.SendPropertyChanged("TAX_NUM");
					this.OnTAX_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(15)")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(30)")]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this.OnFIRSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRSTNAME = value;
					this.SendPropertyChanged("FIRSTNAME");
					this.OnFIRSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIDINITIAL", DbType="VarChar(21)")]
		public string MIDINITIAL
		{
			get
			{
				return this._MIDINITIAL;
			}
			set
			{
				if ((this._MIDINITIAL != value))
				{
					this.OnMIDINITIALChanging(value);
					this.SendPropertyChanging();
					this._MIDINITIAL = value;
					this.SendPropertyChanged("MIDINITIAL");
					this.OnMIDINITIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="VarChar(20)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this.OnFAXChanging(value);
					this.SendPropertyChanging();
					this._FAX = value;
					this.SendPropertyChanged("FAX");
					this.OnFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFDATE
		{
			get
			{
				return this._MODIFDATE;
			}
			set
			{
				if ((this._MODIFDATE != value))
				{
					this.OnMODIFDATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFDATE = value;
					this.SendPropertyChanged("MODIFDATE");
					this.OnMODIFDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFFLOGID", DbType="Int")]
		public System.Nullable<int> STAFFLOGID
		{
			get
			{
				return this._STAFFLOGID;
			}
			set
			{
				if ((this._STAFFLOGID != value))
				{
					this.OnSTAFFLOGIDChanging(value);
					this.SendPropertyChanging();
					this._STAFFLOGID = value;
					this.SendPropertyChanged("STAFFLOGID");
					this.OnSTAFFLOGIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_NUMBER", DbType="VarChar(25)")]
		public string CC_NUMBER
		{
			get
			{
				return this._CC_NUMBER;
			}
			set
			{
				if ((this._CC_NUMBER != value))
				{
					this.OnCC_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._CC_NUMBER = value;
					this.SendPropertyChanged("CC_NUMBER");
					this.OnCC_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_EXPIRY", DbType="VarChar(5)")]
		public string CC_EXPIRY
		{
			get
			{
				return this._CC_EXPIRY;
			}
			set
			{
				if ((this._CC_EXPIRY != value))
				{
					this.OnCC_EXPIRYChanging(value);
					this.SendPropertyChanging();
					this._CC_EXPIRY = value;
					this.SendPropertyChanged("CC_EXPIRY");
					this.OnCC_EXPIRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_CARDHOLDER", DbType="VarChar(50)")]
		public string CC_CARDHOLDER
		{
			get
			{
				return this._CC_CARDHOLDER;
			}
			set
			{
				if ((this._CC_CARDHOLDER != value))
				{
					this.OnCC_CARDHOLDERChanging(value);
					this.SendPropertyChanging();
					this._CC_CARDHOLDER = value;
					this.SendPropertyChanged("CC_CARDHOLDER");
					this.OnCC_CARDHOLDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_ID", DbType="Int")]
		public System.Nullable<int> CC_ID
		{
			get
			{
				return this._CC_ID;
			}
			set
			{
				if ((this._CC_ID != value))
				{
					this.OnCC_IDChanging(value);
					this.SendPropertyChanging();
					this._CC_ID = value;
					this.SendPropertyChanged("CC_ID");
					this.OnCC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_TEMPLATE", DbType="Int")]
		public System.Nullable<int> CC_TEMPLATE
		{
			get
			{
				return this._CC_TEMPLATE;
			}
			set
			{
				if ((this._CC_TEMPLATE != value))
				{
					this.OnCC_TEMPLATEChanging(value);
					this.SendPropertyChanging();
					this._CC_TEMPLATE = value;
					this.SendPropertyChanged("CC_TEMPLATE");
					this.OnCC_TEMPLATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FBALANCE", DbType="Money")]
		public System.Nullable<decimal> FBALANCE
		{
			get
			{
				return this._FBALANCE;
			}
			set
			{
				if ((this._FBALANCE != value))
				{
					this.OnFBALANCEChanging(value);
					this.SendPropertyChanging();
					this._FBALANCE = value;
					this.SendPropertyChanged("FBALANCE");
					this.OnFBALANCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EBALANCE", DbType="Money")]
		public System.Nullable<decimal> EBALANCE
		{
			get
			{
				return this._EBALANCE;
			}
			set
			{
				if ((this._EBALANCE != value))
				{
					this.OnEBALANCEChanging(value);
					this.SendPropertyChanging();
					this._EBALANCE = value;
					this.SendPropertyChanged("EBALANCE");
					this.OnEBALANCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNT", DbType="Real")]
		public System.Nullable<float> DISCOUNT
		{
			get
			{
				return this._DISCOUNT;
			}
			set
			{
				if ((this._DISCOUNT != value))
				{
					this.OnDISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNT = value;
					this.SendPropertyChanged("DISCOUNT");
					this.OnDISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_TYPE_ID", DbType="Int")]
		public System.Nullable<int> CLIENT_TYPE_ID
		{
			get
			{
				return this._CLIENT_TYPE_ID;
			}
			set
			{
				if ((this._CLIENT_TYPE_ID != value))
				{
					this.OnCLIENT_TYPE_IDChanging(value);
					this.SendPropertyChanging();
					this._CLIENT_TYPE_ID = value;
					this.SendPropertyChanged("CLIENT_TYPE_ID");
					this.OnCLIENT_TYPE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> TRANSDATE
		{
			get
			{
				return this._TRANSDATE;
			}
			set
			{
				if ((this._TRANSDATE != value))
				{
					this.OnTRANSDATEChanging(value);
					this.SendPropertyChanging();
					this._TRANSDATE = value;
					this.SendPropertyChanged("TRANSDATE");
					this.OnTRANSDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_INVOICE_NUM", DbType="VarChar(25)")]
		public string LAST_INVOICE_NUM
		{
			get
			{
				return this._LAST_INVOICE_NUM;
			}
			set
			{
				if ((this._LAST_INVOICE_NUM != value))
				{
					this.OnLAST_INVOICE_NUMChanging(value);
					this.SendPropertyChanging();
					this._LAST_INVOICE_NUM = value;
					this.SendPropertyChanged("LAST_INVOICE_NUM");
					this.OnLAST_INVOICE_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCTEMPLATEID", DbType="Int")]
		public System.Nullable<int> ACCTEMPLATEID
		{
			get
			{
				return this._ACCTEMPLATEID;
			}
			set
			{
				if ((this._ACCTEMPLATEID != value))
				{
					this.OnACCTEMPLATEIDChanging(value);
					this.SendPropertyChanging();
					this._ACCTEMPLATEID = value;
					this.SendPropertyChanged("ACCTEMPLATEID");
					this.OnACCTEMPLATEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrokerID", DbType="Int")]
		public System.Nullable<int> BrokerID
		{
			get
			{
				return this._BrokerID;
			}
			set
			{
				if ((this._BrokerID != value))
				{
					this.OnBrokerIDChanging(value);
					this.SendPropertyChanging();
					this._BrokerID = value;
					this.SendPropertyChanged("BrokerID");
					this.OnBrokerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPEPRNINVOICE_ID", DbType="Int")]
		public System.Nullable<int> TYPEPRNINVOICE_ID
		{
			get
			{
				return this._TYPEPRNINVOICE_ID;
			}
			set
			{
				if ((this._TYPEPRNINVOICE_ID != value))
				{
					this.OnTYPEPRNINVOICE_IDChanging(value);
					this.SendPropertyChanging();
					this._TYPEPRNINVOICE_ID = value;
					this.SendPropertyChanged("TYPEPRNINVOICE_ID");
					this.OnTYPEPRNINVOICE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyCC", DbType="Char(1)")]
		public System.Nullable<char> ApplyCC
		{
			get
			{
				return this._ApplyCC;
			}
			set
			{
				if ((this._ApplyCC != value))
				{
					this.OnApplyCCChanging(value);
					this.SendPropertyChanging();
					this._ApplyCC = value;
					this.SendPropertyChanged("ApplyCC");
					this.OnApplyCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="VarChar(3)")]
		public string ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverRating", DbType="Int")]
		public System.Nullable<int> DriverRating
		{
			get
			{
				return this._DriverRating;
			}
			set
			{
				if ((this._DriverRating != value))
				{
					this.OnDriverRatingChanging(value);
					this.SendPropertyChanging();
					this._DriverRating = value;
					this.SendPropertyChanged("DriverRating");
					this.OnDriverRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELETED", DbType="Char(1)")]
		public System.Nullable<char> DELETED
		{
			get
			{
				return this._DELETED;
			}
			set
			{
				if ((this._DELETED != value))
				{
					this.OnDELETEDChanging(value);
					this.SendPropertyChanging();
					this._DELETED = value;
					this.SendPropertyChanged("DELETED");
					this.OnDELETEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanID", DbType="Int NOT NULL")]
		public int PlanID
		{
			get
			{
				return this._PlanID;
			}
			set
			{
				if ((this._PlanID != value))
				{
					this.OnPlanIDChanging(value);
					this.SendPropertyChanging();
					this._PlanID = value;
					this.SendPropertyChanged("PlanID");
					this.OnPlanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasPlan", DbType="Int NOT NULL")]
		public int HasPlan
		{
			get
			{
				return this._HasPlan;
			}
			set
			{
				if ((this._HasPlan != value))
				{
					this.OnHasPlanChanging(value);
					this.SendPropertyChanging();
					this._HasPlan = value;
					this.SendPropertyChanged("HasPlan");
					this.OnHasPlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultTemplateID", DbType="Int NOT NULL")]
		public int DefaultTemplateID
		{
			get
			{
				return this._DefaultTemplateID;
			}
			set
			{
				if ((this._DefaultTemplateID != value))
				{
					this.OnDefaultTemplateIDChanging(value);
					this.SendPropertyChanging();
					this._DefaultTemplateID = value;
					this.SendPropertyChanged("DefaultTemplateID");
					this.OnDefaultTemplateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="VarChar(8)")]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Char(1)")]
		public System.Nullable<char> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EffDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EffDate
		{
			get
			{
				return this._EffDate;
			}
			set
			{
				if ((this._EffDate != value))
				{
					this.OnEffDateChanging(value);
					this.SendPropertyChanging();
					this._EffDate = value;
					this.SendPropertyChanged("EffDate");
					this.OnEffDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TilDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TilDate
		{
			get
			{
				return this._TilDate;
			}
			set
			{
				if ((this._TilDate != value))
				{
					this.OnTilDateChanging(value);
					this.SendPropertyChanging();
					this._TilDate = value;
					this.SendPropertyChanged("TilDate");
					this.OnTilDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Closed", DbType="Bit NOT NULL")]
		public bool Closed
		{
			get
			{
				return this._Closed;
			}
			set
			{
				if ((this._Closed != value))
				{
					this.OnClosedChanging(value);
					this.SendPropertyChanging();
					this._Closed = value;
					this.SendPropertyChanged("Closed");
					this.OnClosedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustBarCode", DbType="VarChar(25)")]
		public string CustBarCode
		{
			get
			{
				return this._CustBarCode;
			}
			set
			{
				if ((this._CustBarCode != value))
				{
					this.OnCustBarCodeChanging(value);
					this.SendPropertyChanging();
					this._CustBarCode = value;
					this.SendPropertyChanged("CustBarCode");
					this.OnCustBarCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingContact", DbType="VarChar(51) NOT NULL", CanBeNull=false)]
		public string BillingContact
		{
			get
			{
				return this._BillingContact;
			}
			set
			{
				if ((this._BillingContact != value))
				{
					this.OnBillingContactChanging(value);
					this.SendPropertyChanging();
					this._BillingContact = value;
					this.SendPropertyChanged("BillingContact");
					this.OnBillingContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromptID", DbType="Int")]
		public System.Nullable<int> PromptID
		{
			get
			{
				return this._PromptID;
			}
			set
			{
				if ((this._PromptID != value))
				{
					this.OnPromptIDChanging(value);
					this.SendPropertyChanging();
					this._PromptID = value;
					this.SendPropertyChanged("PromptID");
					this.OnPromptIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCGROUP_ID", DbType="Int NOT NULL")]
		public int ACCGROUP_ID
		{
			get
			{
				return this._ACCGROUP_ID;
			}
			set
			{
				if ((this._ACCGROUP_ID != value))
				{
					this.OnACCGROUP_IDChanging(value);
					this.SendPropertyChanging();
					this._ACCGROUP_ID = value;
					this.SendPropertyChanged("ACCGROUP_ID");
					this.OnACCGROUP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingType", DbType="Int NOT NULL")]
		public int BillingType
		{
			get
			{
				return this._BillingType;
			}
			set
			{
				if ((this._BillingType != value))
				{
					this.OnBillingTypeChanging(value);
					this.SendPropertyChanging();
					this._BillingType = value;
					this.SendPropertyChanged("BillingType");
					this.OnBillingTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InnerRemark", DbType="VarChar(MAX)")]
		public string InnerRemark
		{
			get
			{
				return this._InnerRemark;
			}
			set
			{
				if ((this._InnerRemark != value))
				{
					this.OnInnerRemarkChanging(value);
					this.SendPropertyChanging();
					this._InnerRemark = value;
					this.SendPropertyChanged("InnerRemark");
					this.OnInnerRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_Start", DbType="VarChar(5)")]
		public string CC_Start
		{
			get
			{
				return this._CC_Start;
			}
			set
			{
				if ((this._CC_Start != value))
				{
					this.OnCC_StartChanging(value);
					this.SendPropertyChanging();
					this._CC_Start = value;
					this.SendPropertyChanged("CC_Start");
					this.OnCC_StartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_IssueNumber", DbType="VarChar(20)")]
		public string CC_IssueNumber
		{
			get
			{
				return this._CC_IssueNumber;
			}
			set
			{
				if ((this._CC_IssueNumber != value))
				{
					this.OnCC_IssueNumberChanging(value);
					this.SendPropertyChanging();
					this._CC_IssueNumber = value;
					this.SendPropertyChanged("CC_IssueNumber");
					this.OnCC_IssueNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_SecurityCode", DbType="VarChar(10)")]
		public string CC_SecurityCode
		{
			get
			{
				return this._CC_SecurityCode;
			}
			set
			{
				if ((this._CC_SecurityCode != value))
				{
					this.OnCC_SecurityCodeChanging(value);
					this.SendPropertyChanging();
					this._CC_SecurityCode = value;
					this.SendPropertyChanged("CC_SecurityCode");
					this.OnCC_SecurityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_Address", DbType="VarChar(50)")]
		public string CC_Address
		{
			get
			{
				return this._CC_Address;
			}
			set
			{
				if ((this._CC_Address != value))
				{
					this.OnCC_AddressChanging(value);
					this.SendPropertyChanging();
					this._CC_Address = value;
					this.SendPropertyChanged("CC_Address");
					this.OnCC_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccType", DbType="SmallInt")]
		public System.Nullable<short> AccType
		{
			get
			{
				return this._AccType;
			}
			set
			{
				if ((this._AccType != value))
				{
					this.OnAccTypeChanging(value);
					this.SendPropertyChanging();
					this._AccType = value;
					this.SendPropertyChanged("AccType");
					this.OnAccTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessType", DbType="VarChar(50)")]
		public string BusinessType
		{
			get
			{
				return this._BusinessType;
			}
			set
			{
				if ((this._BusinessType != value))
				{
					this.OnBusinessTypeChanging(value);
					this.SendPropertyChanging();
					this._BusinessType = value;
					this.SendPropertyChanged("BusinessType");
					this.OnBusinessTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultTripToSR", DbType="Char(1)")]
		public System.Nullable<char> DefaultTripToSR
		{
			get
			{
				return this._DefaultTripToSR;
			}
			set
			{
				if ((this._DefaultTripToSR != value))
				{
					this.OnDefaultTripToSRChanging(value);
					this.SendPropertyChanging();
					this._DefaultTripToSR = value;
					this.SendPropertyChanged("DefaultTripToSR");
					this.OnDefaultTripToSRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadUnloadTime", DbType="Int")]
		public System.Nullable<int> LoadUnloadTime
		{
			get
			{
				return this._LoadUnloadTime;
			}
			set
			{
				if ((this._LoadUnloadTime != value))
				{
					this.OnLoadUnloadTimeChanging(value);
					this.SendPropertyChanging();
					this._LoadUnloadTime = value;
					this.SendPropertyChanged("LoadUnloadTime");
					this.OnLoadUnloadTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowAltAddress", DbType="Char(1) NOT NULL")]
		public char AllowAltAddress
		{
			get
			{
				return this._AllowAltAddress;
			}
			set
			{
				if ((this._AllowAltAddress != value))
				{
					this.OnAllowAltAddressChanging(value);
					this.SendPropertyChanging();
					this._AllowAltAddress = value;
					this.SendPropertyChanged("AllowAltAddress");
					this.OnAllowAltAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPFromPhone", DbType="VarChar(20)")]
		public string RPFromPhone
		{
			get
			{
				return this._RPFromPhone;
			}
			set
			{
				if ((this._RPFromPhone != value))
				{
					this.OnRPFromPhoneChanging(value);
					this.SendPropertyChanging();
					this._RPFromPhone = value;
					this.SendPropertyChanged("RPFromPhone");
					this.OnRPFromPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPPickupPhone", DbType="VarChar(20)")]
		public string RPPickupPhone
		{
			get
			{
				return this._RPPickupPhone;
			}
			set
			{
				if ((this._RPPickupPhone != value))
				{
					this.OnRPPickupPhoneChanging(value);
					this.SendPropertyChanging();
					this._RPPickupPhone = value;
					this.SendPropertyChanged("RPPickupPhone");
					this.OnRPPickupPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VipLabel", DbType="VarChar(16)")]
		public string VipLabel
		{
			get
			{
				return this._VipLabel;
			}
			set
			{
				if ((this._VipLabel != value))
				{
					this.OnVipLabelChanging(value);
					this.SendPropertyChanging();
					this._VipLabel = value;
					this.SendPropertyChanged("VipLabel");
					this.OnVipLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustUserReserv", DbType="Char(1) NOT NULL")]
		public char CustUserReserv
		{
			get
			{
				return this._CustUserReserv;
			}
			set
			{
				if ((this._CustUserReserv != value))
				{
					this.OnCustUserReservChanging(value);
					this.SendPropertyChanging();
					this._CustUserReserv = value;
					this.SendPropertyChanged("CustUserReserv");
					this.OnCustUserReservChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowRegularTrips", DbType="Char(1) NOT NULL")]
		public char ShowRegularTrips
		{
			get
			{
				return this._ShowRegularTrips;
			}
			set
			{
				if ((this._ShowRegularTrips != value))
				{
					this.OnShowRegularTripsChanging(value);
					this.SendPropertyChanging();
					this._ShowRegularTrips = value;
					this.SendPropertyChanged("ShowRegularTrips");
					this.OnShowRegularTripsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAccount", DbType="Char(1) NOT NULL")]
		public char BillingAccount
		{
			get
			{
				return this._BillingAccount;
			}
			set
			{
				if ((this._BillingAccount != value))
				{
					this.OnBillingAccountChanging(value);
					this.SendPropertyChanging();
					this._BillingAccount = value;
					this.SendPropertyChanged("BillingAccount");
					this.OnBillingAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWebAccount", DbType="Char(1) NOT NULL")]
		public char IsWebAccount
		{
			get
			{
				return this._IsWebAccount;
			}
			set
			{
				if ((this._IsWebAccount != value))
				{
					this.OnIsWebAccountChanging(value);
					this.SendPropertyChanging();
					this._IsWebAccount = value;
					this.SendPropertyChanged("IsWebAccount");
					this.OnIsWebAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkipZoneLandmarkPricingForAccounts", DbType="Char(1) NOT NULL")]
		public char SkipZoneLandmarkPricingForAccounts
		{
			get
			{
				return this._SkipZoneLandmarkPricingForAccounts;
			}
			set
			{
				if ((this._SkipZoneLandmarkPricingForAccounts != value))
				{
					this.OnSkipZoneLandmarkPricingForAccountsChanging(value);
					this.SendPropertyChanging();
					this._SkipZoneLandmarkPricingForAccounts = value;
					this.SendPropertyChanged("SkipZoneLandmarkPricingForAccounts");
					this.OnSkipZoneLandmarkPricingForAccountsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPAccDestAddrReq", DbType="Char(1)")]
		public System.Nullable<char> RPAccDestAddrReq
		{
			get
			{
				return this._RPAccDestAddrReq;
			}
			set
			{
				if ((this._RPAccDestAddrReq != value))
				{
					this.OnRPAccDestAddrReqChanging(value);
					this.SendPropertyChanging();
					this._RPAccDestAddrReq = value;
					this.SendPropertyChanged("RPAccDestAddrReq");
					this.OnRPAccDestAddrReqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MDTAccSignReq", DbType="Char(1) NOT NULL")]
		public char MDTAccSignReq
		{
			get
			{
				return this._MDTAccSignReq;
			}
			set
			{
				if ((this._MDTAccSignReq != value))
				{
					this.OnMDTAccSignReqChanging(value);
					this.SendPropertyChanging();
					this._MDTAccSignReq = value;
					this.SendPropertyChanged("MDTAccSignReq");
					this.OnMDTAccSignReqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_CustUser", Storage="_CustUsers", ThisKey="CustomerID", OtherKey="CustomerID")]
		public EntitySet<CustUser> CustUsers
		{
			get
			{
				return this._CustUsers;
			}
			set
			{
				this._CustUsers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CustUsers(CustUser entity)
		{
			this.SendPropertyChanging();
			entity.Customer = this;
		}
		
		private void detach_CustUsers(CustUser entity)
		{
			this.SendPropertyChanging();
			entity.Customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustUser")]
	public partial class CustUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Name;
		
		private string _CustomerID;
		
		private string _ImportantNotes;
		
		private string _Notes;
		
		private string _LoyalPointsNum;
		
		private string _CustUserBarCode;
		
		private int _UserID;
		
		private int _OwnerID;
		
		private int _OwnerType;
		
		private System.Nullable<char> _Status;
		
		private string _Title;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _CellPhone;
		
		private string _Email1;
		
		private string _Email2;
		
		private System.Nullable<int> _HomeAddrID;
		
		private System.Nullable<int> _DriverRating;
		
		private System.Nullable<char> _Priority;
		
		private System.Nullable<char> _CallBack;
		
		private System.Nullable<char> _TextBack;
		
		private System.Nullable<char> _EmailBack;
		
		private string _Web_LoginID;
		
		private string _Web_Password;
		
		private System.Nullable<char> _Web_Admin;
		
		private string _Position;
		
		private System.Nullable<int> _CallbackPhone;
		
		private System.Nullable<int> _EMailbackAddress;
		
		private char _Deleted;
		
		private System.Nullable<char> _WebReservation;
		
		private string _DeletedBy;
		
		private System.Nullable<char> _UserDefaultTripToSR;
		
		private System.Nullable<int> _LoadUnloadTime;
		
		private string _Apt;
		
		private char _AllowAltAddress;
		
		private System.Nullable<int> _PromptID;
		
		private char _CanBook4Other;
		
		private string _VIPNum;
		
		private string _RPFromPhone;
		
		private string _RPPickupPhone;
		
		private string _InnerRemark;
		
		private System.Nullable<char> _ShowRemarkFlag;
		
		private char _ShowRegularTrips;
		
		private char _ReceiptBack;
		
		private string _PhoneHome;
		
		private EntityRef<Customer> _Customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCustomerIDChanging(string value);
    partial void OnCustomerIDChanged();
    partial void OnImportantNotesChanging(string value);
    partial void OnImportantNotesChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnLoyalPointsNumChanging(string value);
    partial void OnLoyalPointsNumChanged();
    partial void OnCustUserBarCodeChanging(string value);
    partial void OnCustUserBarCodeChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnOwnerIDChanging(int value);
    partial void OnOwnerIDChanged();
    partial void OnOwnerTypeChanging(int value);
    partial void OnOwnerTypeChanged();
    partial void OnStatusChanging(System.Nullable<char> value);
    partial void OnStatusChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnCellPhoneChanging(string value);
    partial void OnCellPhoneChanged();
    partial void OnEmail1Changing(string value);
    partial void OnEmail1Changed();
    partial void OnEmail2Changing(string value);
    partial void OnEmail2Changed();
    partial void OnHomeAddrIDChanging(System.Nullable<int> value);
    partial void OnHomeAddrIDChanged();
    partial void OnDriverRatingChanging(System.Nullable<int> value);
    partial void OnDriverRatingChanged();
    partial void OnPriorityChanging(System.Nullable<char> value);
    partial void OnPriorityChanged();
    partial void OnCallBackChanging(System.Nullable<char> value);
    partial void OnCallBackChanged();
    partial void OnTextBackChanging(System.Nullable<char> value);
    partial void OnTextBackChanged();
    partial void OnEmailBackChanging(System.Nullable<char> value);
    partial void OnEmailBackChanged();
    partial void OnWeb_LoginIDChanging(string value);
    partial void OnWeb_LoginIDChanged();
    partial void OnWeb_PasswordChanging(string value);
    partial void OnWeb_PasswordChanged();
    partial void OnWeb_AdminChanging(System.Nullable<char> value);
    partial void OnWeb_AdminChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnCallbackPhoneChanging(System.Nullable<int> value);
    partial void OnCallbackPhoneChanged();
    partial void OnEMailbackAddressChanging(System.Nullable<int> value);
    partial void OnEMailbackAddressChanged();
    partial void OnDeletedChanging(char value);
    partial void OnDeletedChanged();
    partial void OnWebReservationChanging(System.Nullable<char> value);
    partial void OnWebReservationChanged();
    partial void OnDeletedByChanging(string value);
    partial void OnDeletedByChanged();
    partial void OnUserDefaultTripToSRChanging(System.Nullable<char> value);
    partial void OnUserDefaultTripToSRChanged();
    partial void OnLoadUnloadTimeChanging(System.Nullable<int> value);
    partial void OnLoadUnloadTimeChanged();
    partial void OnAptChanging(string value);
    partial void OnAptChanged();
    partial void OnAllowAltAddressChanging(char value);
    partial void OnAllowAltAddressChanged();
    partial void OnPromptIDChanging(System.Nullable<int> value);
    partial void OnPromptIDChanged();
    partial void OnCanBook4OtherChanging(char value);
    partial void OnCanBook4OtherChanged();
    partial void OnVIPNumChanging(string value);
    partial void OnVIPNumChanged();
    partial void OnRPFromPhoneChanging(string value);
    partial void OnRPFromPhoneChanged();
    partial void OnRPPickupPhoneChanging(string value);
    partial void OnRPPickupPhoneChanged();
    partial void OnInnerRemarkChanging(string value);
    partial void OnInnerRemarkChanged();
    partial void OnShowRemarkFlagChanging(System.Nullable<char> value);
    partial void OnShowRemarkFlagChanged();
    partial void OnShowRegularTripsChanging(char value);
    partial void OnShowRegularTripsChanged();
    partial void OnReceiptBackChanging(char value);
    partial void OnReceiptBackChanged();
    partial void OnPhoneHomeChanging(string value);
    partial void OnPhoneHomeChanged();
    #endregion
		
		public CustUser()
		{
			this._Customer = default(EntityRef<Customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					if (this._Customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportantNotes", DbType="VarChar(255)")]
		public string ImportantNotes
		{
			get
			{
				return this._ImportantNotes;
			}
			set
			{
				if ((this._ImportantNotes != value))
				{
					this.OnImportantNotesChanging(value);
					this.SendPropertyChanging();
					this._ImportantNotes = value;
					this.SendPropertyChanged("ImportantNotes");
					this.OnImportantNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(255)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoyalPointsNum", DbType="VarChar(20)")]
		public string LoyalPointsNum
		{
			get
			{
				return this._LoyalPointsNum;
			}
			set
			{
				if ((this._LoyalPointsNum != value))
				{
					this.OnLoyalPointsNumChanging(value);
					this.SendPropertyChanging();
					this._LoyalPointsNum = value;
					this.SendPropertyChanged("LoyalPointsNum");
					this.OnLoyalPointsNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustUserBarCode", DbType="VarChar(25)")]
		public string CustUserBarCode
		{
			get
			{
				return this._CustUserBarCode;
			}
			set
			{
				if ((this._CustUserBarCode != value))
				{
					this.OnCustUserBarCodeChanging(value);
					this.SendPropertyChanging();
					this._CustUserBarCode = value;
					this.SendPropertyChanged("CustUserBarCode");
					this.OnCustUserBarCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this.OnOwnerIDChanging(value);
					this.SendPropertyChanging();
					this._OwnerID = value;
					this.SendPropertyChanged("OwnerID");
					this.OnOwnerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerType", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int OwnerType
		{
			get
			{
				return this._OwnerType;
			}
			set
			{
				if ((this._OwnerType != value))
				{
					this.OnOwnerTypeChanging(value);
					this.SendPropertyChanging();
					this._OwnerType = value;
					this.SendPropertyChanged("OwnerType");
					this.OnOwnerTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1)")]
		public System.Nullable<char> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(15)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(30)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(30)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellPhone", DbType="VarChar(20)")]
		public string CellPhone
		{
			get
			{
				return this._CellPhone;
			}
			set
			{
				if ((this._CellPhone != value))
				{
					this.OnCellPhoneChanging(value);
					this.SendPropertyChanging();
					this._CellPhone = value;
					this.SendPropertyChanged("CellPhone");
					this.OnCellPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email1", DbType="VarChar(50)")]
		public string Email1
		{
			get
			{
				return this._Email1;
			}
			set
			{
				if ((this._Email1 != value))
				{
					this.OnEmail1Changing(value);
					this.SendPropertyChanging();
					this._Email1 = value;
					this.SendPropertyChanged("Email1");
					this.OnEmail1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email2", DbType="VarChar(50)")]
		public string Email2
		{
			get
			{
				return this._Email2;
			}
			set
			{
				if ((this._Email2 != value))
				{
					this.OnEmail2Changing(value);
					this.SendPropertyChanging();
					this._Email2 = value;
					this.SendPropertyChanged("Email2");
					this.OnEmail2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeAddrID", DbType="Int")]
		public System.Nullable<int> HomeAddrID
		{
			get
			{
				return this._HomeAddrID;
			}
			set
			{
				if ((this._HomeAddrID != value))
				{
					this.OnHomeAddrIDChanging(value);
					this.SendPropertyChanging();
					this._HomeAddrID = value;
					this.SendPropertyChanged("HomeAddrID");
					this.OnHomeAddrIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverRating", DbType="Int")]
		public System.Nullable<int> DriverRating
		{
			get
			{
				return this._DriverRating;
			}
			set
			{
				if ((this._DriverRating != value))
				{
					this.OnDriverRatingChanging(value);
					this.SendPropertyChanging();
					this._DriverRating = value;
					this.SendPropertyChanged("DriverRating");
					this.OnDriverRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Char(1)")]
		public System.Nullable<char> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallBack", DbType="Char(1)")]
		public System.Nullable<char> CallBack
		{
			get
			{
				return this._CallBack;
			}
			set
			{
				if ((this._CallBack != value))
				{
					this.OnCallBackChanging(value);
					this.SendPropertyChanging();
					this._CallBack = value;
					this.SendPropertyChanged("CallBack");
					this.OnCallBackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextBack", DbType="Char(1)")]
		public System.Nullable<char> TextBack
		{
			get
			{
				return this._TextBack;
			}
			set
			{
				if ((this._TextBack != value))
				{
					this.OnTextBackChanging(value);
					this.SendPropertyChanging();
					this._TextBack = value;
					this.SendPropertyChanged("TextBack");
					this.OnTextBackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailBack", DbType="Char(1)")]
		public System.Nullable<char> EmailBack
		{
			get
			{
				return this._EmailBack;
			}
			set
			{
				if ((this._EmailBack != value))
				{
					this.OnEmailBackChanging(value);
					this.SendPropertyChanging();
					this._EmailBack = value;
					this.SendPropertyChanged("EmailBack");
					this.OnEmailBackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web_LoginID", DbType="VarChar(50)")]
		public string Web_LoginID
		{
			get
			{
				return this._Web_LoginID;
			}
			set
			{
				if ((this._Web_LoginID != value))
				{
					this.OnWeb_LoginIDChanging(value);
					this.SendPropertyChanging();
					this._Web_LoginID = value;
					this.SendPropertyChanged("Web_LoginID");
					this.OnWeb_LoginIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web_Password", DbType="VarChar(100)")]
		public string Web_Password
		{
			get
			{
				return this._Web_Password;
			}
			set
			{
				if ((this._Web_Password != value))
				{
					this.OnWeb_PasswordChanging(value);
					this.SendPropertyChanging();
					this._Web_Password = value;
					this.SendPropertyChanged("Web_Password");
					this.OnWeb_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web_Admin", DbType="Char(1)")]
		public System.Nullable<char> Web_Admin
		{
			get
			{
				return this._Web_Admin;
			}
			set
			{
				if ((this._Web_Admin != value))
				{
					this.OnWeb_AdminChanging(value);
					this.SendPropertyChanging();
					this._Web_Admin = value;
					this.SendPropertyChanged("Web_Admin");
					this.OnWeb_AdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="VarChar(30)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallbackPhone", DbType="Int")]
		public System.Nullable<int> CallbackPhone
		{
			get
			{
				return this._CallbackPhone;
			}
			set
			{
				if ((this._CallbackPhone != value))
				{
					this.OnCallbackPhoneChanging(value);
					this.SendPropertyChanging();
					this._CallbackPhone = value;
					this.SendPropertyChanged("CallbackPhone");
					this.OnCallbackPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMailbackAddress", DbType="Int")]
		public System.Nullable<int> EMailbackAddress
		{
			get
			{
				return this._EMailbackAddress;
			}
			set
			{
				if ((this._EMailbackAddress != value))
				{
					this.OnEMailbackAddressChanging(value);
					this.SendPropertyChanging();
					this._EMailbackAddress = value;
					this.SendPropertyChanged("EMailbackAddress");
					this.OnEMailbackAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Char(1) NOT NULL")]
		public char Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebReservation", DbType="Char(1)")]
		public System.Nullable<char> WebReservation
		{
			get
			{
				return this._WebReservation;
			}
			set
			{
				if ((this._WebReservation != value))
				{
					this.OnWebReservationChanging(value);
					this.SendPropertyChanging();
					this._WebReservation = value;
					this.SendPropertyChanged("WebReservation");
					this.OnWebReservationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserDefaultTripToSR", DbType="Char(1)")]
		public System.Nullable<char> UserDefaultTripToSR
		{
			get
			{
				return this._UserDefaultTripToSR;
			}
			set
			{
				if ((this._UserDefaultTripToSR != value))
				{
					this.OnUserDefaultTripToSRChanging(value);
					this.SendPropertyChanging();
					this._UserDefaultTripToSR = value;
					this.SendPropertyChanged("UserDefaultTripToSR");
					this.OnUserDefaultTripToSRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadUnloadTime", DbType="Int")]
		public System.Nullable<int> LoadUnloadTime
		{
			get
			{
				return this._LoadUnloadTime;
			}
			set
			{
				if ((this._LoadUnloadTime != value))
				{
					this.OnLoadUnloadTimeChanging(value);
					this.SendPropertyChanging();
					this._LoadUnloadTime = value;
					this.SendPropertyChanged("LoadUnloadTime");
					this.OnLoadUnloadTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apt", DbType="VarChar(30)")]
		public string Apt
		{
			get
			{
				return this._Apt;
			}
			set
			{
				if ((this._Apt != value))
				{
					this.OnAptChanging(value);
					this.SendPropertyChanging();
					this._Apt = value;
					this.SendPropertyChanged("Apt");
					this.OnAptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowAltAddress", DbType="Char(1) NOT NULL")]
		public char AllowAltAddress
		{
			get
			{
				return this._AllowAltAddress;
			}
			set
			{
				if ((this._AllowAltAddress != value))
				{
					this.OnAllowAltAddressChanging(value);
					this.SendPropertyChanging();
					this._AllowAltAddress = value;
					this.SendPropertyChanged("AllowAltAddress");
					this.OnAllowAltAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromptID", DbType="Int")]
		public System.Nullable<int> PromptID
		{
			get
			{
				return this._PromptID;
			}
			set
			{
				if ((this._PromptID != value))
				{
					this.OnPromptIDChanging(value);
					this.SendPropertyChanging();
					this._PromptID = value;
					this.SendPropertyChanged("PromptID");
					this.OnPromptIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanBook4Other", DbType="Char(1) NOT NULL")]
		public char CanBook4Other
		{
			get
			{
				return this._CanBook4Other;
			}
			set
			{
				if ((this._CanBook4Other != value))
				{
					this.OnCanBook4OtherChanging(value);
					this.SendPropertyChanging();
					this._CanBook4Other = value;
					this.SendPropertyChanged("CanBook4Other");
					this.OnCanBook4OtherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPNum", DbType="VarChar(50)")]
		public string VIPNum
		{
			get
			{
				return this._VIPNum;
			}
			set
			{
				if ((this._VIPNum != value))
				{
					this.OnVIPNumChanging(value);
					this.SendPropertyChanging();
					this._VIPNum = value;
					this.SendPropertyChanged("VIPNum");
					this.OnVIPNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPFromPhone", DbType="VarChar(20)")]
		public string RPFromPhone
		{
			get
			{
				return this._RPFromPhone;
			}
			set
			{
				if ((this._RPFromPhone != value))
				{
					this.OnRPFromPhoneChanging(value);
					this.SendPropertyChanging();
					this._RPFromPhone = value;
					this.SendPropertyChanged("RPFromPhone");
					this.OnRPFromPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPPickupPhone", DbType="VarChar(20)")]
		public string RPPickupPhone
		{
			get
			{
				return this._RPPickupPhone;
			}
			set
			{
				if ((this._RPPickupPhone != value))
				{
					this.OnRPPickupPhoneChanging(value);
					this.SendPropertyChanging();
					this._RPPickupPhone = value;
					this.SendPropertyChanged("RPPickupPhone");
					this.OnRPPickupPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InnerRemark", DbType="VarChar(254)")]
		public string InnerRemark
		{
			get
			{
				return this._InnerRemark;
			}
			set
			{
				if ((this._InnerRemark != value))
				{
					this.OnInnerRemarkChanging(value);
					this.SendPropertyChanging();
					this._InnerRemark = value;
					this.SendPropertyChanged("InnerRemark");
					this.OnInnerRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowRemarkFlag", DbType="Char(1)")]
		public System.Nullable<char> ShowRemarkFlag
		{
			get
			{
				return this._ShowRemarkFlag;
			}
			set
			{
				if ((this._ShowRemarkFlag != value))
				{
					this.OnShowRemarkFlagChanging(value);
					this.SendPropertyChanging();
					this._ShowRemarkFlag = value;
					this.SendPropertyChanged("ShowRemarkFlag");
					this.OnShowRemarkFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowRegularTrips", DbType="Char(1) NOT NULL")]
		public char ShowRegularTrips
		{
			get
			{
				return this._ShowRegularTrips;
			}
			set
			{
				if ((this._ShowRegularTrips != value))
				{
					this.OnShowRegularTripsChanging(value);
					this.SendPropertyChanging();
					this._ShowRegularTrips = value;
					this.SendPropertyChanged("ShowRegularTrips");
					this.OnShowRegularTripsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptBack", DbType="Char(1) NOT NULL")]
		public char ReceiptBack
		{
			get
			{
				return this._ReceiptBack;
			}
			set
			{
				if ((this._ReceiptBack != value))
				{
					this.OnReceiptBackChanging(value);
					this.SendPropertyChanging();
					this._ReceiptBack = value;
					this.SendPropertyChanged("ReceiptBack");
					this.OnReceiptBackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneHome", DbType="VarChar(20)")]
		public string PhoneHome
		{
			get
			{
				return this._PhoneHome;
			}
			set
			{
				if ((this._PhoneHome != value))
				{
					this.OnPhoneHomeChanging(value);
					this.SendPropertyChanging();
					this._PhoneHome = value;
					this.SendPropertyChanged("PhoneHome");
					this.OnPhoneHomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_CustUser", Storage="_Customer", ThisKey="CustomerID", OtherKey="CustomerID", IsForeignKey=true)]
		public Customer Customer
		{
			get
			{
				return this._Customer.Entity;
			}
			set
			{
				Customer previousValue = this._Customer.Entity;
				if (((previousValue != value) 
							|| (this._Customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer.Entity = null;
						previousValue.CustUsers.Remove(this);
					}
					this._Customer.Entity = value;
					if ((value != null))
					{
						value.CustUsers.Add(this);
						this._CustomerID = value.CustomerID;
					}
					else
					{
						this._CustomerID = default(string);
					}
					this.SendPropertyChanged("Customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
